[build]
  functions = "netlify/functions"
  command = "npm install && npm run build"
  publish = "build"
  environment = { DATABASE_URL = "postgresql://neondb_owner:npg_Ar4WMIKpdOR5@ep-spring-frost-a1y4wsvc-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require" }

[[plugins]]
  package = "@netlify/plugin-functions-installation"
