[build]
  functions = "functions"
  command = "pip install -r requirements.txt && python app.py"
  publish = "build"

  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200