"""Add section to Recipe

Revision ID: 1628c0cc39a0
Revises: 
Create Date: 2025-03-16 11:57:40.957293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1628c0cc39a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=255), nullable=True))  # Changed to nullable=True
        batch_op.alter_column('recipe_total_cost',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('recipe_total_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('section')

    # ### end Alembic commands ###
